# Lakebase Postgres Workload Sizing Configuration
# This template collects user inputs for Postgres instance sizing and cost estimation

# Database Instance Unit Configuration
database_instance:
  # Bulk writes from Delta table for initial data loading and batch updates
  bulk_writes_per_second: 0
  
  # Continuous writes from Delta table for real-time order processing
  continuous_writes_per_second: 0
  
  # Read operations for customer lookups, product searches
  reads_per_second: 0
  
  # Read replicas for analytics and reporting
  number_of_readable_secondaries: 0
  readable_secondary_size_cu: 1

  # Lakebase Promotion percentage (0-100)
  promotion_percentage: 50.0

# Database Storage Configuration
database_storage:
  # Total data size including all tables and indexes
  data_stored_gb: 0
  
  # Daily data cleanup 
  estimated_data_deleted_daily_gb: 0

  # Restore windows for data recovery (days)
  restore_windows_days: 0

# Delta Synchronization Configuration
delta_synchronization:
  # Real-time sync for critical data
  number_of_continuous_pipelines: 0
  
  # Batch sync for analytics data
  expected_data_per_sync_gb: 0
  
  # Use snapshot for consistent analytics
  sync_mode: SNAPSHOT
  
  # Run analytics sync daily
  sync_frequency: "Per day"

  tables_to_sync:
    - name: samples.tpcds_sf1.customer
      primary_keys: [c_customer_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.customer_address
      primary_keys: [ca_address_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.customer_demographics
      primary_keys: [cd_demo_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.store_sales
      primary_keys: [ss_item_sk, ss_ticket_number]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.item
      primary_keys: [i_item_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.date_dim
      primary_keys: [d_date_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.store
      primary_keys: [s_store_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.inventory
      primary_keys: [inv_date_sk, inv_item_sk, inv_warehouse_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.warehouse
      primary_keys: [w_warehouse_sk]
      scheduling_policy: SNAPSHOT
    - name: samples.tpcds_sf1.promotion
      primary_keys: [p_promo_sk]
      scheduling_policy: SNAPSHOT

