# Lakebase Postgres Concurrency Testing Configuration
# This configuration defines test scenarios for evaluating Postgres performance
# under various concurrency patterns and workload types.

# Postgres Connection Configuration
postgres_connection:
  # Connection details (can reference secrets or config files)
  host: "${POSTGRES_HOST}"
  port: 5432
  database: "${POSTGRES_DATABASE}"
  username: "${POSTGRES_USERNAME}"
  password: "${POSTGRES_PASSWORD}"
  
  # SSL Configuration
  ssl_mode: "require"
  ssl_cert_path: ""
  ssl_key_path: ""
  ssl_ca_path: ""
  
  # Connection Pool Settings for Testing
  initial_pool_size: 10
  max_pool_size: 100
  pool_timeout: 30
  connection_timeout: 30
  query_timeout: 300  # 5 minutes max per query

# Test Environment Settings
test_environment:
  # Test duration and timing
  default_test_duration: 300  # 5 minutes in seconds
  warmup_duration: 30         # 30 seconds warmup
  cooldown_duration: 15       # 15 seconds cooldown
  
  # Data collection intervals
  metrics_collection_interval: 5  # seconds
  progress_report_interval: 30    # seconds
  
  # Test execution settings
  max_retries: 3
  retry_delay: 5  # seconds
  
  # Output configuration
  results_directory: "./test_results"
  detailed_logging: true
  save_query_results: false  # Set to true to save actual query results

# Test Scenarios
test_scenarios:
  
  # Scenario 1: OLTP Simulation
  - name: "oltp_light"
    description: "Light OLTP workload simulation with typical e-commerce queries"
    duration: 300  # 5 minutes
    concurrent_connections: 25
    ramp_up_duration: 30
    ramp_down_duration: 15
    
    query_patterns:
      - query_name: "customer_lookup"
        weight: 30  # 30% of queries
        think_time: 0.1  # 100ms between queries
        max_execution_time: 5  # 5 seconds timeout
        
      - query_name: "order_details"
        weight: 25
        think_time: 0.2
        max_execution_time: 10
        
      - query_name: "inventory_check"
        weight: 20
        think_time: 0.1
        max_execution_time: 3
        
      - query_name: "product_catalog"
        weight: 15
        think_time: 0.5
        max_execution_time: 8
        
      - query_name: "store_locator"
        weight: 10
        think_time: 0.3
        max_execution_time: 5
    
    # Performance expectations
    performance_targets:
      avg_response_time_ms: 500
      p95_response_time_ms: 2000
      p99_response_time_ms: 5000
      min_throughput_qps: 50
      max_error_rate_percent: 1
  
  # Scenario 2: OLTP Heavy Load
  - name: "oltp_heavy"
    description: "Heavy OLTP workload with high concurrency"
    duration: 600  # 10 minutes
    concurrent_connections: 75
    ramp_up_duration: 60
    ramp_down_duration: 30
    
    query_patterns:
      - query_name: "customer_lookup"
        weight: 35
        think_time: 0.05
        max_execution_time: 3
        
      - query_name: "order_details"
        weight: 30
        think_time: 0.1
        max_execution_time: 8
        
      - query_name: "inventory_check"
        weight: 25
        think_time: 0.05
        max_execution_time: 2
        
      - query_name: "customer_recent_orders"
        weight: 10
        think_time: 0.2
        max_execution_time: 10
    
    performance_targets:
      avg_response_time_ms: 800
      p95_response_time_ms: 3000
      p99_response_time_ms: 8000
      min_throughput_qps: 120
      max_error_rate_percent: 2
  
  # Scenario 3: OLAP Analytics
  - name: "olap_analytics"
    description: "Analytics workload with complex queries and lower concurrency"
    duration: 900  # 15 minutes
    concurrent_connections: 15
    ramp_up_duration: 60
    ramp_down_duration: 30
    
    query_patterns:
      - query_name: "daily_sales_summary"
        weight: 40
        think_time: 5.0  # 5 seconds between queries
        max_execution_time: 60
        
      - query_name: "customer_service_lookup"
        weight: 35
        think_time: 3.0
        max_execution_time: 45
        
      - query_name: "inventory_multi_location"
        weight: 25
        think_time: 8.0
        max_execution_time: 120
    
    performance_targets:
      avg_response_time_ms: 15000  # 15 seconds
      p95_response_time_ms: 45000  # 45 seconds
      p99_response_time_ms: 90000  # 90 seconds
      min_throughput_qps: 2
      max_error_rate_percent: 5
  
  # Scenario 4: Mixed Workload
  - name: "mixed_workload"
    description: "Mixed OLTP and OLAP workload representing real-world usage"
    duration: 600  # 10 minutes
    concurrent_connections: 50
    ramp_up_duration: 45
    ramp_down_duration: 30
    
    query_patterns:
      # OLTP queries (70% of workload)
      - query_name: "customer_lookup"
        weight: 25
        think_time: 0.2
        max_execution_time: 5
        
      - query_name: "order_details"
        weight: 20
        think_time: 0.3
        max_execution_time: 10
        
      - query_name: "inventory_check"
        weight: 15
        think_time: 0.1
        max_execution_time: 3
        
      - query_name: "product_catalog"
        weight: 10
        think_time: 0.5
        max_execution_time: 8
        
      # OLAP queries (30% of workload)
      - query_name: "daily_sales_summary"
        weight: 20
        think_time: 10.0
        max_execution_time: 60
        
      - query_name: "customer_service_lookup"
        weight: 10
        think_time: 15.0
        max_execution_time: 45
    
    performance_targets:
      avg_response_time_ms: 2000
      p95_response_time_ms: 8000
      p99_response_time_ms: 30000
      min_throughput_qps: 25
      max_error_rate_percent: 3
  
  # Scenario 5: Stress Test
  - name: "stress_test"
    description: "High-stress scenario to find system limits"
    duration: 300  # 5 minutes
    concurrent_connections: 150
    ramp_up_duration: 60
    ramp_down_duration: 30
    
    query_patterns:
      - query_name: "customer_lookup"
        weight: 50
        think_time: 0.01
        max_execution_time: 10
        
      - query_name: "inventory_check"
        weight: 30
        think_time: 0.01
        max_execution_time: 5
        
      - query_name: "order_details"
        weight: 20
        think_time: 0.05
        max_execution_time: 15
    
    performance_targets:
      avg_response_time_ms: 2000
      p95_response_time_ms: 10000
      p99_response_time_ms: 30000
      min_throughput_qps: 80
      max_error_rate_percent: 10  # Higher tolerance for stress test
  
  # Scenario 6: Spike Test
  - name: "spike_test"
    description: "Test system behavior during traffic spikes"
    duration: 420  # 7 minutes total
    concurrent_connections: 25  # Base load
    ramp_up_duration: 30
    ramp_down_duration: 30
    
    # Spike configuration
    spikes:
      - start_time: 120  # 2 minutes into test
        duration: 60     # 1 minute spike
        spike_connections: 100
        
      - start_time: 240  # 4 minutes into test
        duration: 90     # 1.5 minute spike
        spike_connections: 80
    
    query_patterns:
      - query_name: "customer_lookup"
        weight: 40
        think_time: 0.1
        max_execution_time: 5
        
      - query_name: "order_details"
        weight: 35
        think_time: 0.2
        max_execution_time: 10
        
      - query_name: "inventory_check"
        weight: 25
        think_time: 0.1
        max_execution_time: 3
    
    performance_targets:
      avg_response_time_ms: 1000
      p95_response_time_ms: 5000
      p99_response_time_ms: 15000
      min_throughput_qps: 30
      max_error_rate_percent: 5

# Query Definitions
# These reference the converted Postgres queries from the target directory
queries:
  customer_lookup:
    file_path: "./queries/target/oltp_q01_customer_lookup.sql"
    parameters:
      - name: "customer_id"
        type: "integer"
        generation: "random_range"
        range: [1, 10000]
      - name: "email_domain"
        type: "string"
        generation: "random_choice"
        choices: ["gmail.com", "yahoo.com", "company.com", "example.org"]
    
  order_details:
    file_path: "./queries/target/oltp_q02_order_details.sql"
    parameters:
      - name: "order_id"
        type: "integer"
        generation: "random_range"
        range: [1, 50000]
      - name: "customer_id"
        type: "integer"
        generation: "random_range"
        range: [1, 10000]
    
  inventory_check:
    file_path: "./queries/target/oltp_q03_inventory_check.sql"
    parameters:
      - name: "product_id"
        type: "integer"
        generation: "random_range"
        range: [1, 1000]
      - name: "store_id"
        type: "integer"
        generation: "random_range"
        range: [1, 50]
    
  customer_recent_orders:
    file_path: "./queries/target/oltp_q04_customer_recent_orders.sql"
    parameters:
      - name: "customer_id"
        type: "integer"
        generation: "random_range"
        range: [1, 10000]
      - name: "days_back"
        type: "integer"
        generation: "random_range"
        range: [7, 90]
    
  product_catalog:
    file_path: "./queries/target/oltp_q05_product_catalog.sql"
    parameters:
      - name: "category_id"
        type: "integer"
        generation: "random_range"
        range: [1, 20]
      - name: "price_range_min"
        type: "decimal"
        generation: "random_range"
        range: [10.00, 100.00]
    
  promotion_lookup:
    file_path: "./queries/target/oltp_q06_promotion_lookup.sql"
    parameters:
      - name: "promo_code"
        type: "string"
        generation: "random_choice"
        choices: ["SAVE10", "WELCOME", "SPRING2024", "SUMMER25", "FALL30"]
    
  store_locator:
    file_path: "./queries/target/oltp_q07_store_locator.sql"
    parameters:
      - name: "zip_code"
        type: "string"
        generation: "random_choice"
        choices: ["10001", "90210", "60601", "77001", "30301"]
      - name: "radius_miles"
        type: "integer"
        generation: "random_range"
        range: [5, 25]
    
  daily_sales_summary:
    file_path: "./queries/target/oltp_q08_daily_sales_summary.sql"
    parameters:
      - name: "report_date"
        type: "date"
        generation: "random_date_range"
        start_date: "2024-01-01"
        end_date: "2024-12-31"
      - name: "store_id"
        type: "integer"
        generation: "random_range"
        range: [1, 50]
    
  customer_service_lookup:
    file_path: "./queries/target/oltp_sp01_customer_service_lookup.sql"
    parameters:
      - name: "customer_id"
        type: "integer"
        generation: "random_range"
        range: [1, 10000]
      - name: "include_orders"
        type: "boolean"
        generation: "random_choice"
        choices: [true, false]
    
  inventory_multi_location:
    file_path: "./queries/target/oltp_sp02_inventory_multi_location.sql"
    parameters:
      - name: "product_ids"
        type: "integer_array"
        generation: "random_array"
        array_size: [3, 10]
        element_range: [1, 1000]
      - name: "location_type"
        type: "string"
        generation: "random_choice"
        choices: ["warehouse", "store", "all"]

# Performance Metrics Collection
metrics:
  # Core Performance Metrics
  response_time:
    enabled: true
    percentiles: [50, 75, 90, 95, 99, 99.9]
    histogram_buckets: [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
  
  throughput:
    enabled: true
    measurement_window: 10  # seconds
    include_failed_requests: false
  
  error_rate:
    enabled: true
    error_categories:
      - "connection_timeout"
      - "query_timeout"
      - "syntax_error"
      - "permission_denied"
      - "connection_lost"
      - "other"
  
  connection_metrics:
    enabled: true
    track_pool_utilization: true
    track_connection_lifecycle: true
    track_idle_connections: true
  
  # Postgres-Specific Metrics
  postgres_metrics:
    enabled: true
    collection_interval: 15  # seconds
    
    # Database-level metrics
    database_stats:
      - "pg_stat_database"
      - "pg_stat_bgwriter"
      - "pg_stat_archiver"
    
    # Table-level metrics (for queries being tested)
    table_stats:
      - "pg_stat_user_tables"
      - "pg_statio_user_tables"
      - "pg_stat_user_indexes"
    
    # Connection and activity metrics
    activity_stats:
      - "pg_stat_activity"
      - "pg_locks"
    
    # Performance metrics
    performance_stats:
      - "pg_stat_statements"  # Requires pg_stat_statements extension
    
  # System Resource Metrics (if accessible)
  system_metrics:
    enabled: false  # Enable if running on system with access
    cpu_usage: true
    memory_usage: true
    disk_io: true
    network_io: true

# Alerting and Monitoring
alerting:
  enabled: true
  
  # Real-time alerts during testing
  real_time_alerts:
    - metric: "error_rate"
      threshold: 10  # percent
      duration: 30   # seconds
      action: "log_warning"
    
    - metric: "avg_response_time"
      threshold: 10000  # milliseconds
      duration: 60
      action: "log_warning"
    
    - metric: "connection_pool_utilization"
      threshold: 90  # percent
      duration: 30
      action: "log_warning"
  
  # Test completion alerts
  completion_alerts:
    - condition: "test_completed"
      action: "generate_report"
    
    - condition: "test_failed"
      action: "log_error"
    
    - condition: "performance_targets_missed"
      action: "highlight_in_report"

# Reporting Configuration
reporting:
  # Report formats
  formats:
    - "json"      # Machine-readable
    - "html"      # Human-readable with charts
    - "csv"       # For spreadsheet analysis
    - "markdown"  # For documentation
  
  # Report content
  include_sections:
    - "executive_summary"
    - "test_configuration"
    - "performance_metrics"
    - "error_analysis"
    - "postgres_insights"
    - "recommendations"
    - "raw_data"
  
  # Chart and visualization settings
  charts:
    response_time_timeline: true
    throughput_timeline: true
    error_rate_timeline: true
    percentile_comparison: true
    connection_pool_usage: true
    postgres_performance_trends: true
  
  # Report customization
  custom_analysis:
    compare_scenarios: true
    capacity_recommendations: true
    bottleneck_identification: true
    scaling_projections: true

# Advanced Configuration
advanced:
  # Connection Management
  connection_strategy: "pool"  # pool, individual, mixed
  connection_validation: true
  connection_retry_logic: true
  
  # Query Execution
  prepared_statements: true
  query_plan_analysis: false  # Requires elevated permissions
  explain_slow_queries: true
  slow_query_threshold: 5000  # milliseconds
  
  # Data Management
  cleanup_test_data: false
  preserve_temp_tables: false
  
  # Debugging and Troubleshooting
  debug_mode: false
  verbose_logging: false
  capture_network_traces: false
  save_connection_logs: true
