# Databricks App configuration for deployment
# Based on: https://apps-cookbook.dev/docs/fastapi/getting_started/create
apiVersion: v1
kind: databricks-app
metadata:
  name: lakebase-accelerator
  description: "Databricks Lakebase Accelerator - Cost estimation and configuration generator"

spec:
  # App configuration
  display_name: "Lakebase Accelerator"
  description: "Configure OLTP workload parameters, estimate Lakebase costs, and generate deployment configurations"
  
  # Container configuration
  image:
    name: lakebase-accelerator
    tag: latest
    
  # Runtime configuration
  resources:
    cpu: "1"
    memory: "2Gi"
    
  # Port configuration
  port: 8000
  
  # Environment variables (these should be set in Databricks App environment)
  env:
    - name: DATABRICKS_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: databricks-credentials
          key: access_token
    - name: DATABRICKS_SERVER_HOSTNAME
      valueFrom:
        secretKeyRef:
          name: databricks-credentials
          key: server_hostname
    - name: DATABRICKS_HTTP_PATH
      valueFrom:
        secretKeyRef:
          name: databricks-credentials
          key: http_path
    - name: DATABRICKS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: databricks-credentials
          key: endpoint
    - name: MODEL_NAME
      value: "databricks-meta-llama-3-1-70b-instruct"
      
  # Health check configuration
  healthCheck:
    path: "/health"
    port: 8000
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    
  # App permissions and access
  permissions:
    - compute_access: true
    - sql_warehouse_access: true
    - unity_catalog_access: true