/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TestingRouteImport } from './../routes/testing'
import { Route as DocsRouteImport } from './../routes/docs'
import { Route as DeploymentRouteImport } from './../routes/deployment'
import { Route as CostRouteImport } from './../routes/cost'
import { Route as BestPracticesRouteImport } from './../routes/best-practices'
import { Route as IndexRouteImport } from './../routes/index'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPracticesRoute = BestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-practices': typeof BestPracticesRoute
  '/cost': typeof CostRoute
  '/deployment': typeof DeploymentRoute
  '/docs': typeof DocsRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-practices': typeof BestPracticesRoute
  '/cost': typeof CostRoute
  '/deployment': typeof DeploymentRoute
  '/docs': typeof DocsRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-practices': typeof BestPracticesRoute
  '/cost': typeof CostRoute
  '/deployment': typeof DeploymentRoute
  '/docs': typeof DocsRoute
  '/testing': typeof TestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-practices'
    | '/cost'
    | '/deployment'
    | '/docs'
    | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/best-practices' | '/cost' | '/deployment' | '/docs' | '/testing'
  id:
    | '__root__'
    | '/'
    | '/best-practices'
    | '/cost'
    | '/deployment'
    | '/docs'
    | '/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestPracticesRoute: typeof BestPracticesRoute
  CostRoute: typeof CostRoute
  DeploymentRoute: typeof DeploymentRoute
  DocsRoute: typeof DocsRoute
  TestingRoute: typeof TestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-practices': {
      id: '/best-practices'
      path: '/best-practices'
      fullPath: '/best-practices'
      preLoaderRoute: typeof BestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestPracticesRoute: BestPracticesRoute,
  CostRoute: CostRoute,
  DeploymentRoute: DeploymentRoute,
  DocsRoute: DocsRoute,
  TestingRoute: TestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
